logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: info
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        dbcp2:
            driver-class-name: com.mysql.cj.jdbc.Driver
        password: Relaxism^*^BBU5980
        url: jdbc:mysql://127.0.0.1:3306/
        username: LotteON

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_spl: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/
    servlet:
        multipart:
            location: src/main/resources/static/file
            max-file-size: 10MB